### ISSUE TITLE
no log delieved via gmail

### ISSUE THREAD

**Issue by ghoxt007** [xp4xbox/Python-Keylogger#2]
did everything you said and followed the instruction carefully, but couldn't receive logs via gmail, is there something i'm doing wrong, please help

**Comment by ghoxt007** [comment]
Please help logs not delivering to email

**Comment by xp4xbox** [comment]
Your account must have allowed access for less secure apps.

**Comment by ghoxt007** [comment]
Thanks for replying, i did that but right now I’m trying to run it and it
says “failed to execute script main” help pls

**Comment by xp4xbox** [comment]
Hmm, try running the `.py` file in a powershell window and see what the error is.

**Comment by ghoxt007** [comment]
Ok seen the issue let me see if I can fix it, if I can’t I will let you know...
Thanks

**Comment by ghoxt007** [comment]
Ok the issue is from arc import persistence tool,
ctypes, wmi, win32event, win32api, winerror, os, shutil, winreg

**Comment by xp4xbox** [comment]
Can i see the full output?

**Comment by ghoxt007** [comment]
From src import persistence, tools
File “..\src\persistence.py”, line 1, in <module> 
Import ctypes, wmi, win32event, win32api, winerror, os, shutil, winreg

**Comment by ghoxt007** [comment]
ModulenotFoundError: No module named ‘wmi’

**Comment by xp4xbox** [comment]
Oh I forgot to add wmi to requirements.

**Comment by xp4xbox** [comment]
Just updated the requirements, install it and it should work now.

**Comment by ghoxt007** [comment]
Ok thanks

**Comment by ghoxt007** [comment]
Every thing works fine got a message in my mail,
but no keylogs

**Comment by xp4xbox** [comment]
not sure it works for me

**Comment by xp4xbox** [comment]
try running it in a powershell window again, and see if there is an error.

**Comment by ghoxt007** [comment]
Wow your job is great it also bring mouse click... can I be your student please 🙏🏻

**Comment by ghoxt007** [comment]
It sends logs and stop sending and doesn’t work in every site

**Comment by xp4xbox** [comment]
What do you mean stop sending.

**Comment by ghoxt007** [comment]
it doesn't send all key logs, and it also stops sending,

**Comment by ghoxt007** [comment]
i tried to run it again every works fine but no keylog. loging into my gmail it doesnt bring passowrd or email address only logs the site i visit and then it stops logging

**Comment by xp4xbox** [comment]
try running it in a powershell window again, and see if there is an error.
