### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by chiragarora01** [xp4xbox/Python-Keylogger#3]

**Comment by xp4xbox** [comment]
try running it first without building it as an .exe and see what the error is.

**Comment by ArisCuber19** [comment]
same error here and I can't find a way to make it work... any help? :D

**Comment by xp4xbox** [comment]
It seems to be pyinstaller related, for now you can fix it by just running the .py file instead of the .exe

**Comment by xp4xbox** [comment]
Was due to pynput newest version, reinstall the requirements.txt should fix it.
